name: bulild
on:
  push:
    branches:
      -master
  pull_request:
jobs:
  build:
    name: build
    run-on: ubuntu-20.04
     steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
      run:
        docker build -t juice-shop: ${{github.sha}} .
        
      
  
